### ISSUE TITLE
这个项目仅限于北京理工大学官网吗？我在尝试其他网站代理时默认都是生成的北京理工的官网。

### ISSUE THREAD

**Issue by 1637936665** [spencerwooo/bit-webvpn-converter#259]
**Is your feature request related to a problem? Please describe.**
这个项目仅限于北京理工大学官网吗？我在尝试其他网站代理时默认都是生成的北京理工的官网。
**Describe the solution you'd like**
我的想法是可以代理转换任意网站，例如谷歌搜索，百度，等等
**Describe alternatives you've considered**

**Additional context**
![微信图片_20240511175954](https://github.com/spencerwooo/bit-webvpn-converter/assets/74756259/8499321e-0915-49bb-9856-2ed6e6664a1f)

**Comment by phy25** [comment]
如果您不是北京理工大学的师生教职工或是有关产品的用户，恐怕您并无法使用这个项目。

**Comment by spencerwooo** [comment]
> 我的想法是可以代理转换任意网站，例如谷歌搜索，百度，等等

@1637936665 这没有任何意义，本项目仅和北理工校内资源访问相关。
