### ISSUE TITLE
Browser filled input does not properly initialize input state

### ISSUE THREAD

**Issue by phy25** [spencerwooo/bit-webvpn-converter#3]
To reproduce in Chrome:

1. Visit https://webvpn.vercel.app/
2. Type http://www.bit.edu.cn/ in the input
3. In the same tab, navigate to https://spencerwoo.com/
4. Press back button in the browser. The webapp will show up again with the input populated with "http://www.bit.edu.cn/" by the browser
5. Press CONVERT
    - Expected: the URL will be converted
    - Actual: Prompting "You'll need to specify a URL first.". When clicking on the original URL, the input text recovered by the browser will get cleared.

**Comment by phy25** [comment]
The new version still doesn't immediately convert the browser-recovered input. However by changing the URL a bit it does trigger the conversion.

By the way nice design for v2!

**Comment by spencerwooo** [comment]
> The new version still doesn't immediately convert the browser-recovered input.

I used a `useDebounce` hook so as to not trigger the convert on each input keystroke, so a bit change is required to trigger the conversion.

**Comment by phy25** [comment]
Looks like this is working now, thanks!
