### ISSUE TITLE
Library VPN in BIT has changed to nlibvpn

### ISSUE THREAD

**Issue by lsylusiyao** [spencerwooo/bit-webvpn-converter#34]
Currently `libvpn` has been integrated into `lib.bit.edu.cn` and the `libvpn` has been converted to `nlibvpn`. So please change the rule of conversion for `Library VPN`.

**Comment by spencerwooo** [comment]
Is this a simple find and replace, i.e.,

```diff
-  lib: 'https://libvpn.bit.edu.cn',
+  lib: 'https://nlibvpn.bit.edu.cn',
```

or are there any more changes required?

**Comment by lsylusiyao** [comment]
Yes, just a simple replacement. I've already checked the website inside the school.
